schema_version: 1.0.0
time_window_days: 7
seed: null
actors:
- u_alex
- u_riley
- u_jamie
audience_weights:
  Exec: 3
  Ops: 2
  Eng: 1
nlq:
  count: 800
  success_rate: 0.65
  slow_rate: 0.1
  uncertain_rate: 0.05
  gaps_distribution:
    missing_asset: 0.1
    missing_column: 0.12
    grain_mismatch: 0.06
    type_mismatch: 0.05
    freshness_breach: 0.08
    joinability_issue: 0.05
    access_denied: 0.03
    docs_missing: 0.12
    performance_limit: 0.04
slack:
  threads: 60
  replies_mean: 4
email:
  threads: 20
  replies_mean: 3
catalog:
  domains:
  - orders
  - customers
  - products
  - marketing
  mart_tables: 10
  staging_tables: 20
  freshness_sla_hours:
  - 24
  - 48
  - 72
  inject_freshness_breaches: 0.15
