name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pre-commit
          pip install pytest

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run unit tests
        run: pytest -q

      - name: Build pack and report
        run: |
          datagap-synth init || true
          datagap-synth gen --config config.yaml --out packs/ci --seed 424242
          datagap-report gen --pack packs/ci --out out/ci --llm off
          datagap-report validate --pack packs/ci

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-ci
          path: out/ci
